### ISSUE TITLE
doesn't work with @storybook/react package

### ISSUE THREAD

**Issue by udisun** [Kilix/storybook-addon-jsx#19]
```
Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
Error: Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
    at AddonStore.getChannel (http://localhost:9001/static/preview.bundle.js:25606:15)
    at Object.addWithJSX (http://localhost:9001/static/preview.bundle.js:128442:36)
    at Object.api.(anonymous function) [as addWithJSX] (http://localhost:9001/static/preview.bundle.js:126362:17)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:185918:46)
    at Object._typeof (http://localhost:9001/static/preview.bundle.js:185921:30)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:678:30)
    at fn (http://localhost:9001/static/preview.bundle.js:88:20)
    at webpackContext (http://localhost:9001/static/preview.bundle.js:162996:9)
    at http://localhost:9001/static/preview.bundle.js:109747:12
    at Array.forEach (<anonymous>)
```

**Comment by alexandrebodin** [comment]
Hi @udisun,

Can you tell us what is your current storybook version ?

**Comment by chrisopedia** [comment]
I'm getting this error: (@storybook/react: ^3.2.16)

```
ReferenceError: setAddOn is not defined
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:71554:1)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:71566:30)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:679:30)
    at fn (http://localhost:9001/static/preview.bundle.js:89:20)
    at webpackContext (http://localhost:9001/static/preview.bundle.js:71498:9)
    at http://localhost:9001/static/preview.bundle.js:57800:16
    at Array.forEach (<anonymous>)
    at loadStories (http://localhost:9001/static/preview.bundle.js:57799:16)
    at ConfigApi._renderMain (http://localhost:9001/static/preview.bundle.js:58747:20)
    at render (http://localhost:9001/static/preview.bundle.js:58773:17)```

**Comment by chrisopedia** [comment]
Nevermind, I got it to work.

**Comment by autr** [comment]
@chrisopedia How?
